### ISSUE TITLE
Typo: buffer 10 times larger than necessary

### ISSUE THREAD

**Issue by gnbl** [EmanuelFeru/hoverboard-firmware-hack-FOC#1]
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/master/Src/comms.c#L20

**Comment by gnbl** [comment]
didn't see the string output. but still, it could be smaller.

**Comment by EmanuelFeru** [comment]
Indeed seems on the high side. I will check this part of the code and update it if necessary.

**Comment by EmanuelFeru** [comment]
I checked, Better to keep it as it is to avoid any future issues in case someone extends it.
