### ISSUE TITLE
What is inside bldc model

### ISSUE THREAD

**Issue by AntumArk** [EmanuelFeru/hoverboard-firmware-hack-FOC#10]
Hello, 

Is there a way to take a look what is inside BLDC model plant? (mexw64 file)

**Comment by EmanuelFeru** [comment]
Yes, it is possible if you have Matlab, you just need to open BLDCmotorControl_FOC_R2017b_fixdt.slx. At the moment I did not create a webview from the whole model, only the BLDC_Controller itself. 
If you are interested about the motor model, I use the one available in Matlab. This one:
https://nl.mathworks.com/help/physmod/sps/powersys/ref/permanentmagnetsynchronousmachine.html

Does this answer your question?

**Comment by AntumArk** [comment]
Yes, thank you!
