### ISSUE TITLE
Support for single mainboard with a GD32F103RCT6

### ISSUE THREAD

**Issue by ciafe** [EmanuelFeru/hoverboard-firmware-hack-FOC#100]
Hello,
Is the mainboard version available for GD? It's stated in the readme but I can't found it, just the dual boars version for GD.

I got a hoverboard to build my project and it has the GD instead the ST...

Thanks!

**Comment by Candas1** [comment]
Hi,

Same firmware works with both stm and gd boards. Have you tried to flash it?

**Comment by ciafe** [comment]
Ooh, I was not aware that GD was a clone of ST! 😅 I was expecting different startup, peripherals,...
 I did not tried yesterday, but after your feedback I've done just now and I flashed it perfectly!

Thank a lot for the quick feedback!
