### ISSUE TITLE
LCD Debug 

### ISSUE THREAD

**Issue by hunty1987** [EmanuelFeru/hoverboard-firmware-hack-FOC#102]
im trying to get the lcd debug feature to work as im just getting beeping after flashing the hovercard variant.
i have enabled:
// ############################### DEBUG LCD ###############################
#define DEBUG_I2C_LCD             // standard 16x2 or larger text-lcd via i2c-converter on right sensor board cable
// ########################### END OF DEBUG LCD ############################
and disabled:
  //#define FEEDBACK_SERIAL_USART3        // right sensor board cable, disable if I2C (nunchuk or lcd) is used!
  // #define DEBUG_SERIAL_USART3           // right sensor board cable, disable if I2C (nunchuk or lcd) is used!
is there anything else that needs doing as all im getting on the screen is "hover 2.0 initi" on line 2, line one is blank.
can someone please point me in the right direction to fix this so i can debug the other issue im having.

**Comment by EmanuelFeru** [comment]
@hunty1987 I didn't work with LCD, maybe in the future. But from your description it seems the data is not displayed.
If you find the solution please create a Pull Request.
