### ISSUE TITLE
Will ferromagnetic material close to the stator cause issue?

### ISSUE THREAD

**Issue by Coo-per** [EmanuelFeru/hoverboard-firmware-hack-FOC#109]
Hi,

I plan to drill 4-5 holes in the motor near the axel bearing and place bolts in those holes. Will the bolts being attracted to the magnetic field cause disruption to the motors functioning? What kind of disturbance is to be expected: Max speed decrease, torque decrease, power inefficiency - major, minor, or none?

Thanks,
Cooper

![b79d0e3467c6812b1d1aa333e58de0cddf587625](https://user-images.githubusercontent.com/11779632/97509280-1d4aaf80-193f-11eb-9868-fd9f590f6043.png)

**Comment by benjaf** [comment]
I have made the same modification to some of my motors, and they seem to behave no differently. With 10" wheels mounted on the rotor they perform very similarly to the standard 10" motors.
