### ISSUE TITLE
Wheels not moving but showing speed in arduino serial monitor

### ISSUE THREAD

**Issue by mike6003** [EmanuelFeru/hoverboard-firmware-hack-FOC#114]
Hello,

could you please say if the issue with the wheels not moving is already known and has a solution?

Facts:
- STM32 board
- VARIANT_USAR firmware
- Arduino Uno (also tried on Mega 2560)
- Wheels are not moving using /Arduino/hoverserial/hoverserial.ino
- If I move them manually - I can see speed changes in the arduino serial monitor log
- Both wheels are connected
- No error beeps (if I start without serial connection - it's beeping 3 times)

Could you please say if it's a known issue, maybe I missed something or how would you debug this issue?

Thanks in advance and kind regards, Mike

**Comment by EmanuelFeru** [comment]
I think you just need to the auto calibration, see the wiki page. Because first time it doesn't know what input type do you have.
To avoid auto calibration you can specify your input type in config.h for Variant USART. If you use the arduino example, set it to Normal input type.

**Comment by mike6003** [comment]
Hi Emmanuel,
thanks for your quick reply.
I tried with RoboDurden/hoverboard-firmware-hack and it worked for me.
Kind regards, Mike
