### ISSUE TITLE
Using multiple motors on shared shaft to increase torque and power.

### ISSUE THREAD

**Issue by Istria1704** [EmanuelFeru/hoverboard-firmware-hack-FOC#115]
Hello guys,

Let me first start by thanking everyone involved in this scene for all their effort and making a lot of mechatronics projects possible on a budget. This is not really an "issue". I'm just wondering what your thoughts are about it.

Has anyone ever tried to put multiple hub motors on the same (custom) driveshaft to increase torque and power? I suppose at one time we will run out of the stock controller's power capacity, but what are other issues that could occur?

Has anyone ever done something like this? Or connected multiple motors to the same output in another way (like chains, belts, etc.)?

**Comment by EmanuelFeru** [comment]
I think there are some people that did the things you mention. You should join our Telegram group and check it out (link in readme).
