### ISSUE TITLE
Piggyback motherboard variant in IO Hawk hoverboard

### ISSUE THREAD

**Issue by vamfun** [EmanuelFeru/hoverboard-firmware-hack-FOC#130]
Since my hoverboard Hover-1 H1 motherboard quit (#129) I got a $35 used IO Hawk to hack.  Unfortunately it has the STM32 mounted on a separate board that plugs into a motor driver board like a shield. ![image](https://user-images.githubusercontent.com/4359767/105277684-bcef9680-5b58-11eb-91be-b727d3dff666.jpeg)
Bottom of stm board showing sockets.
![image](https://user-images.githubusercontent.com/4359767/105277751-e14b7300-5b58-11eb-8604-9781c3de20df.jpeg)
Here is the driver board
![image](https://user-images.githubusercontent.com/4359767/105277787-f58f7000-5b58-11eb-992e-79cd254d0343.jpeg)

This is a 4 to 5 year old board and it uses Infineon ir2136s drivers.   

I'm reluctant to flash it since the configuration appears quite different.   
Has anyone had experience with this ?

Teardown blog post [https://vamfun.wordpress.com/2021/01/20/flying-firehose-blog-2-io-hawk-hoverboard-teardown/]

**Comment by Candas1** [comment]
Hi, 

It's a monster, I have never seen such a mainboard before.

Even the chip is different, it has 100 pins it seems.
![image](https://user-images.githubusercontent.com/20670049/105405147-17f1be00-5c2b-11eb-9273-0488893a78f8.png)

I am not an expert, but I imagine it would take a lot of time to make it work and you might not encounter such a board again.

As you said I would restore it to a hoverboard.

**Comment by EmanuelFeru** [comment]
The `STM32F103VCT6`(your board) and  `STM32F103RCT6`(supported one), they both make part from the same family `STM32F103xC`. So, the properties seem to be similar, but as Candas said I doubt that it will work out of the box.. and I don't recommend trying it to avoid damaging something.

Overall, the board looks as better quality and I think upon some checking of the pinout, and configuration it should not be very difficult to port the code to this new board... it is just a matter of who is willing to take the challenge 😊

**Comment by Candas1** [comment]
I ended up with like 20 mainboards with stm32f103vct6 chips directly on the same pcb.
Looks like I am the one to take the challenge.
Stay tuned

**Comment by Any2suited66** [comment]
I know it's been awhile but were you able to flash the firmware on this board, @Candas1.  I've got two of them in my garage.
