### ISSUE TITLE
Quo Vadis this. ?

### ISSUE THREAD

**Issue by RoboDurden** [EmanuelFeru/hoverboard-firmware-hack-FOC#133]
I may unleash the full rant tomorrow. Also it is already late here in Germany.

I recommend this fork in every youtube comment and have made it the default in my new online compiler: https://pionierland.de/hoverhack/

Yet your code gets worse and worse :-(

Not that you makes excessive use of `#ifdef `but even worse you also use `#ifndef `:-(
This makes codes of different variants overlap and when you make changes with `vairant_adc `in mind you create bugs for `variant_usart` :-(

All these many `VARIANT_XY `(of which you stupidly are so proud of), could be run by an ESP32.
So for sure all this functionalities could also go into seperate `variant_xy.c` files.

And `main.c` , etc. should be kept as simple as possible (steer, speed = +-1000 for example)

And if a user has a problem with `variant_adc` he will never even see any `usart` code.

This seperation of functionality could then be the anyway neccessary step to port the firmware to oo.

I still dream that someone with STM32 knowledge will be happy to spend this one hour to make my **oo-fork** start up. And now with my simple IDE it has become even more simple.

Then with the power of inheritance, the three different modes VOLTAGE, SPEED and TORQUE could be derived from one bldc_controller class.
(Which of course would be derived from a gerneric controller class so other programmers could add truly open source FOC code...)

But what i see here is the one-liner obsession from the 80s :-(
You hail yourself when for combining the different voltage+speed+torque code with an array tmp[rtU->z_ctrlModReq] :-(
And the good old cmd1 and cmd2 are turned into 
InputStruct input1[INPUTS_NR] = { {0, 0, 0, PRI_INPUT1}, {0, 0, 0, AUX_INPUT1} };
InputStruct input2[INPUTS_NR] = { {0, 0, 0, PRI_INPUT2}, {0, 0, 0, AUX_INPUT2} };

And like all the stupid Linux believers you hail to yourselves that only the genius rules the chaos..
But this is going nowhere and sooner or later someone else has to start all over and all your hard work gets abondend :'(

Of course i understand that your time is limited and that we all mostly want to spend it on adding new features.
But without a greater vision, this will only lead into destructon.

So my propsal is to clean the code from all these different variants and put them into 

`#ifdef VARIANT_XY include "variant_xy.h"`

to start with :-)

Roland, the little physicist :-)
Good night and good luck :-/

**Comment by EmanuelFeru** [comment]
Mr Durden,

With all my respect. If you think you can do a much better job than others then do it. Stop arguing about others people code! Be constructive and not destructive.
If you think this firmware is so bad, remove if from your compiler and videos. Do not use it anymore. I will also remove the link to your compiler here.
Make a better firmware and the let the facts speak for themselves. This is the world of open source. No need for words.
Good luck with coding!
