### ISSUE TITLE
ADC variant does not work...troubleshooting?

### ISSUE THREAD

**Issue by epikao** [EmanuelFeru/hoverboard-firmware-hack-FOC#136]
Hello,

I ordered two hover electronics boards as shown on the Emanuel front page via Aliexpress + a Nunchuck controller.

With the Nunchuck controller, reverse and forward does not work cleanly. If I push the joystick backwards or forwards, the motor (both) turns mostly in the right direction but not always, and that only one motor turns somehow does not work with the joystick.

I have now programmed the board with the ADC variant, but unfortunately here nothing works.
Interestingly, I have both variants no sound from the buzzer, is that normal?

I just do not know where to look for the error? The board can be switched on, at least an LED lights up.

Or are these Aliexpress boards defective?

Would appreciate any hints.

Many thanks

**Comment by Candas1** [comment]
Do you have a picture or link of the board just in case ?
Not having sound is weird... Could be that the board is little different.

There are little instructions in the [wiki](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Variant-ADC)

**Comment by epikao** [comment]
thanks for your reply. See attached pictures. 
![20210129_191654](https://user-images.githubusercontent.com/26655950/106312550-206b7980-6267-11eb-82b0-f8948c1e1b92.jpg)
![20210129_191713](https://user-images.githubusercontent.com/26655950/106312552-22cdd380-6267-11eb-89c4-c3a06ee9f3a0.jpg)
![20210129_191722](https://user-images.githubusercontent.com/26655950/106312555-24979700-6267-11eb-994c-c21e5f6374f9.jpg)


I'm meaning the below board

**Comment by epikao** [comment]
and here the l

**Comment by epikao** [comment]
I uploaded the generated firmware.bin file via ST-Link software. The build I done with vscode/plio

**Comment by EmanuelFeru** [comment]
@epikao Seems like you have a slightly different board  version, at least at this middle location:
yours:
![image](https://user-images.githubusercontent.com/24780745/106316036-67a83900-626c-11eb-8ff1-8b40a7ce6053.png)
vs. mine:
![image](https://user-images.githubusercontent.com/24780745/106316119-860e3480-626c-11eb-9959-f461aec2d5bf.png)

The coil is a different location. And I am sure because you don't hear the beep and melody, some pins are also changed.
With a multimeter can you identify if your pins are corresponding to [defines.h](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/master/Inc/defines.h)?

If not, then you need to do a small exercise to update the pins similar to [here](https://github.com/NiklasFauth/hoverboard-firmware-hack/issues/162) (but with your pins of course).

**Comment by Candas1** [comment]
OK I was too slow and Emanuel replied ah ah
Yes we expect PA4, on some boards it's mapped to PC13, but those boards had other differences as well.

You can also program directly from vscode/platformio.
To debug ADC you can use [serial debug](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Debug-Serial)

**Comment by EmanuelFeru** [comment]
Luckily, I was around this time :P

**Comment by epikao** [comment]
many thanks, I'm checking all that now. But some more questions:

Does the controller send always some data over the serial? Till now I didn't had success to receive anything.. I'm also not sure if I need the battery power for that, or if only supply over my programmer is enough. With supply of programmer and no battery power the LED switches directly on, so the on/off switch has no function. 
The buzzer is connected via transistor Q6 and Resistor R56 to PA4, so this connection should be according default code, but still no sound. I think the buzzer only works with battery supply because of VSW = 5V? Anyway also with battery supply no sound. Looks I must measure the signal output of PA4....

**Comment by epikao** [comment]
oh Buzzer looks is connected at PA6 not PA4, is that a problem?

**Comment by Candas1** [comment]
Motors are not spinning for safety reasons at startup if cmdL and cmdR are not within -50 to +50 range.
You have to do [input calibration](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Input-Calibration) .

**Comment by epikao** [comment]
> Motors are not spinning for safety reasons at startup if cmdL and cmdR are not within -50 to +50 range.
> You have to do [input calibration](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Input-Calibration) .

ok, I will test this later, now I first want make work this buzzer.
I took my second board, here I found out that with original firmware, the buzzer also works only with programmer supply. That is strange, because according schematic the buzzer should be connected to VSW, and this is also the case on my board. 
After uploading with the Firmware from this side, no more sound... hmm maybe something with the frequency.

**Comment by Candas1** [comment]
Hmm weird, is it a problem on the first board.

**Comment by epikao** [comment]
so yes, something at the buzzer is defective on my first board. 

With the second board buzzer works, and motor are spinning, but both motor spins always together. I couldn't find a position where the one motor stops and the other one is spinning... why that?

And I also not understand that even buzzer is connected at PA6 it works if Software is set at default PA4...

**Comment by Candas1** [comment]
It's not a "tank" style mixing.

![image](https://user-images.githubusercontent.com/20670049/106337587-d946ae00-6291-11eb-9049-8122f2c275c7.png)

**Comment by epikao** [comment]
ok, but I also couldn't find a position where both motor are spinning in the same direction, always spinning in opposite... but will check tomorrow again more carefully. Thanks for your great support.

**Comment by EmanuelFeru** [comment]
Making the buzzer work is a confirmation that the interrupt for motor control is working correctly. So it's a good idea to fix the issue.

Are you sure the buzzer pin is correct? And what chip do you have?
Check buzzer for continuity? Did the board work with factory firmware before you flashed the chip? I always do one check with new boards just to avoid surprises.

**Comment by epikao** [comment]
> Making the buzzer work is a confirmation that the interrupt for motor control is working correctly. So it's a good idea to fix the issue.
> 
> Are you sure the buzzer pin is correct? And what chip do you have?
> Check buzzer for continuity? Did the board work with factory firmware before you flashed the chip? I always do one check with new boards just to avoid surprises.

Thanks! First board with original firmware I can not remember that there was sound from the buzzer, but with my second board. So the buzzer electronics on the first board must have a defect somewhere. The confusion regarding PA4, PA6, was because I checked the wrong controller datasheet.

Unfortunately, I still don't fully understand the spinning behavior of the motors in combination with the states of the ADC inputs:

Following my setup and findings. I never had a state where both motors are spinning in the same direction... also I not understand why some input states make motor not spinning very smoth or very slow, or beep, and sometimes stopping...

![image](https://user-images.githubusercontent.com/26655950/106352846-8a773380-62e6-11eb-8bda-db2e250aaf6e.png)
![image](https://user-images.githubusercontent.com/26655950/106352872-b8f50e80-62e6-11eb-8bf7-e21bd548ec61.png)
![image](https://user-images.githubusercontent.com/26655950/106352887-cd390b80-62e6-11eb-86ea-e2bfbb8e0a12.png)

**Comment by vamfun** [comment]
That is a mystery... Best thing to do is uart print cmd1 and cmd2 to see if they agree with your motor movement.   I think your setup will introduce a lot of noise into the ADC which may account for some of the roughness.   Try grounding all inputs as close to the input plug as possible then run a debug with that input.   Also what steer/speed blending are you using?
How did you specify the type of input...1,2 or 3?  Did you enter autocal?
Maybe use the new repository , comment out auto cal enable , then start with a full erase to make sure auto cal values are not affecting your inputs.  Set your type as 2 and see what you get.

**Comment by epikao** [comment]
#Also what steer/speed blending are you using?
How did you specify the type of input...1,2 or 3? Did you enter autocal?

I did the autocal, but not more, I also not study the other setups, just download the newest code from this respository, build ADC variant and upload... so all other setups should be still default. I was hopping that default should work, but it looks I must study now your mentioned other parameter, and I will record the UART output and maybe do again an autocal...

**Comment by epikao** [comment]
`Also what steer/speed blending are you using?`

And what do you mean with that? I'm using 0V, 3.3V and two 33K resistors to each input do genarate 1.65 V (MID), see setup above.

**Comment by vamfun** [comment]
As I understand it, the default blend is x.5 on steering (blue adc1) and x1 on speed (green adc2) so if green is 1 or -1 the blue cannot cause a reversal until green is at mid. But this doesn't explain your table.   The shutdowns were probably caused by emergency shutdown due to exceeding the ADC timeout count (indicated by beeps) due to high level of noise.
I would also guess that you may need to reverse a hall sensor lead (or change direction in sw) to get motors running in same direction.

**Comment by EmanuelFeru** [comment]
@epikao, for testing purposes I think is easier to use 2 potentiometers and remove the 33k resistors. Because auto-calibration requires that you move the potis thorough the whole range.

And if your motors act roughly it could be that 2 of the motors phases are swapped. Sometimes the colors don't match. Swap the phases and give a try with low input.

Overall to get the ADC variant  running it should be:
- prepare your hardware, connect potis, etc.
- full chip erase
- flash ADC variant
- run auto calibration
- the motors should run

**Comment by epikao** [comment]
`I would also guess that you may need to reverse a hall sensor lead (or change direction in sw) to get motors running in same direction.`

besides EMC, I think this is the main problem.
I have currently already tried different motor phase connection combinations - unfortunately still without success.

Do I have to try the Hall connections as well? Can I not either or? So Hall or motor phases ? It is easier to change the motor phases. Maybe I should also check if the Hall-Sensors are not connected on other pins... but I think then the motor would not spins...

What is the easiest way to find the right combination? Try and error? I could also open the motor cover....

**Comment by EmanuelFeru** [comment]
I think try and error is the easiest. The other way is to use an oscilloscope and log back-emf voltage with Hall sensors. The should match the [motor mapping](https://raw.githubusercontent.com/EmanuelFeru/bldc-motor-control-FOC/master/02_Figures/control_methods.png).
However, from what I heard until now just inter-changing motor phases to find the right combination was sufficient. I didn't hear yet that Hall sensors need to be inter-changed... but I don't exclude it.

**Comment by epikao** [comment]
ok thanks, I couldn't find a combination that works...(I tested with the Nunchuck Variant, with 15V to 3.3V regulator between). At some combination the motor started without touching the Nunchuck, often with very strong shaking. Crazy. Could it be that the mosfetdriver maybe are some on the wrong GPIO's ? I fear that I must now check the whole PIN assignment...

**Comment by epikao** [comment]
I think, I've found the problem. The hall wires Left, are connected to motor phase Left Hi, and so one, so something is swapped and not according pin assignment....

**Comment by Candas1** [comment]
Can you record a video of how it behaves ?
