### ISSUE TITLE
Nunchuk Control

### ISSUE THREAD

**Issue by farev** [EmanuelFeru/hoverboard-firmware-hack-FOC#140]
Hello, I had the nunchuk control working properly and then I updated th firmware and it stopped working. I don't believe my nunchuk is the problem because it was able to work before. I also tried using the code I had used before but is still didn't work. What may be causing this problem?

**Comment by Candas1** [comment]
Can you explain a bit more what you mean by not working? Do you get beeps, no beeps?
If even the old firmware doesn't work, are you sure the wiring is OK?

In case you did the Auto-calibration by mistake, you can either completely delete the chip in stlink utility, or redo the calibration.

**Comment by farev** [comment]
I do get 4 beeps which means a timeout. I have checked the wiring several times but maybe I am connecting something wrong. I am using the right sensor board cables the ground and the two signal wires and I am using the 3.3v pin.

**Comment by Candas1** [comment]
Just to be sure, you are using nunchuk variant right? Not another variant with nunchuk as auxiliary input

**Comment by farev** [comment]
Yes I am using nunchuck variant. And should there be some current passing through the nunchuck because I measured with a voltmeter one end on the 3.3v pin and the other one in the right sensor board ground and I didn’t get nothing.

**Comment by Candas1** [comment]
It could be that your nunchuk is not working anymore ? can you get a spare one ?

**Comment by farev** [comment]
I was able to get a spare nunchuk and I tried it but it still didn't work.

**Comment by farev** [comment]
I tried the USART variant to control it with an arduino and it didn't work either. I got 3 beeps.

**Comment by Candas1** [comment]
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC#diagnostics

Please check the wiring.

**Comment by farev** [comment]
I did a full chip erase and I flashed it again and now the USART variant works. I tried the nunchuk variant and it still didn't work.

**Comment by farev** [comment]
I am modifying the arduino code to be able to use a nunchuk connected to the arduino and using the USART variant. What is the max speed I can go, the test speed is 300 so I don't what is the max value it can go.

**Comment by Candas1** [comment]
Hi,

Range for Steer and speed is -1000 to 1000.

**Comment by farev** [comment]
I haven't tested it yet but it should work. After I test it if it work I will close the issue.

**Comment by farev** [comment]
It is working great!
