### ISSUE TITLE
Connecting with the Hoverboard via ST-Link V2 does not work

### ISSUE THREAD

**Issue by royrobotiks** [EmanuelFeru/hoverboard-firmware-hack-FOC#141]
First of all, thanks for the great work on the hoverboard firmware! I'd like to flash my hoverboard with your firmware in order to control the motors via UART. 

A first try ended already in a sparkling mainboard with smoke. So I ordered a new mainboard, put it in the hoverboard and the hoverboard works again after the replacement. However, I still want to flash another firmware on it and I'm still stuck at the very beginning. I have no clue what might be the problem. I'm also a complete STM32 n00b and Windows10 user, for that matter. Any advice will be highly appreciated! 

Here's what I've done so far: 

- soldered a red wire to the main board's 3.3V connection
- soldered a green wire to the main board's SWCLK 
- soldered a black wire to the main board's GND
- soldered a blue wire to the main board's SWDIO

Then I connected SWCLK, SWDIO and GND with the ST-LINK V2. 3.3V (red wire) is NOT connected.

After that I followed the instructions on https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/How-to-Unlock-MCU-flash - "How to Unlock MCU Flash". And I tried to connect with the controller while the board was powered on via its own battery.

Unfortunately this did not work. The error message was always "can not connect to target!". It asked me to select 'Normal' or 'HotPlug' mode from Target->Settings menu. So I've tried all options but nothing worked. 

I hope anyone can help me. Thanks a lot in advance!

Here are some photos of my setup:

![img_stlink_v2](https://user-images.githubusercontent.com/11241850/107967130-080c9600-6fad-11eb-86c8-e0db534d9ac8.jpg)

![img_stlink_v2_pins](https://user-images.githubusercontent.com/11241850/107967145-0e9b0d80-6fad-11eb-902e-5e456103b872.jpg)

![img_board_connection_close](https://user-images.githubusercontent.com/11241850/107967172-15c21b80-6fad-11eb-9165-672246653cf5.jpg)

![IMG_20210215_160918](https://user-images.githubusercontent.com/11241850/107967188-19ee3900-6fad-11eb-866c-515b7d8d8b2b.jpg)

In case you need more detailed info, please let me know.

**Comment by Candas1** [comment]
Hi, 
Unfortunately this firmware is not compatible with this mainboard variant.
It has a totally different chip and design.

Here is another firmware you can use:
https://github.com/cloidnerux/hoverboard-firmware-hack

**Comment by royrobotiks** [comment]
I'd like to control the two motors via UART. Ultimately, I want to build a line following robot with a raspberyPi & camera, which can move people. 

Thanks a lot for the link! I'll give it a try tomorrow.
