### ISSUE TITLE
Revers

### ISSUE THREAD

**Issue by AndreyShupletsov** [EmanuelFeru/hoverboard-firmware-hack-FOC#144]
Здравствуйте.
Есть ли возможность включать реверс в варианте Hovercar не двойным (тройным ...) нажатием педали тормоз, 
а установкой входа swclk (pa14) или swdio (pa13) d в "1".

**Comment by Candas1** [comment]
Hi,

If you don't post in english you won't get an answer.

**Comment by AndreyShupletsov** [comment]
Ok.

Is there a possibility of polling pin SWCLK or SWDIO in this firmware?

**Comment by Candas1** [comment]
Those pins are not used in the firmware.
You could use it as digital pins but you need to be careful not to prevent flashing.
