### ISSUE TITLE
Having problem with breaks hovercar

### ISSUE THREAD

**Issue by mochiianune** [EmanuelFeru/hoverboard-firmware-hack-FOC#145]
Hi im using the variant hovercar. Got problem with the breaks everytime that i used the break insted of making the wheels to stop or to slow it down it go realy fast. Im making the test run with all the wheels is on the ground and im riding the hovercar. And I did activate the reverse wheel turn. Thanks

**Comment by Candas1** [comment]
Hi. 

How is your setup looking like?
Do you use pedals?
Do you have a video of how it behaves?

**Comment by mochiianune** [comment]
Yes I put to pedals on it. I dont have a video but everytime that I step on the pedal break instead of going slow or stop the wheels turn fast

**Comment by Candas1** [comment]
But throttle works well?

**Comment by mochiianune** [comment]
Yes throttle works really well.

**Comment by mochiianune** [comment]
And reverse go really well also when I step on the break twice

**Comment by Candas1** [comment]
Are you sure your wiring is ok ?

**Comment by EmanuelFeru** [comment]
You can check the Hovercar schematic here: https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Variant HOVERCAR

From the symthoms can it be that the Brake potentiometer is damaged?

**Comment by mochiianune** [comment]
It might be the pot I was suspecting thesame thing coz my wiring was all correct. Im going to switch the pot beetween the break pot and the throtle pot later on

**Comment by EmanuelFeru** [comment]
Fixed?

**Comment by mochiianune** [comment]
Sorry for late reply. I did found the problem it was my motor hall sensor inside the motor. When i change my motor hall sensor everything is running good

**Comment by mochiianune** [comment]
![71097940-F5F8-4803-94DC-2CCA3B81E301](https://user-images.githubusercontent.com/53362470/111857341-07d62200-88ee-11eb-942e-5d0f1f6d88e5.png)

**Comment by EmanuelFeru** [comment]
Good that you found it. Then I will choose this topic.
