### ISSUE TITLE
Do you provide open source hardware pcb?

### ISSUE THREAD

**Issue by mailonghua** [EmanuelFeru/hoverboard-firmware-hack-FOC#146]
Do you provide open source hardware pcb?

**Comment by EmanuelFeru** [comment]
Not sure if I understand, can you be more specific? Because the mainboard pcb is the stock factory for which we have a reversed engineered schematic. Is this what you mean?

**Comment by Ability-dis** [comment]
I think we should design a Pcb exactly like the hoverboard circuit .It will keep this firmware alive and more functions can be added when many people are using the same circuit (No issue of different MCU and availability). Many people will test and improve it. Please consider it seriously.
