### ISSUE TITLE
4WD question

### ISSUE THREAD

**Issue by interlark** [EmanuelFeru/hoverboard-firmware-hack-FOC#152]
Hi! Very interesting project.
There are 2 hoverboards. What's the solution to synchronize the speed of all 4 wheels, any suggestions?

**Comment by EmanuelFeru** [comment]
Depends how are you controlling it and what is your input. The idea is to have both mainboards receive the same input. Just some examples (didn't try myself):
- if you used ADC as input, then you have to make the 2 mainboards GND common, and connect the potentiometer(s) output to both mainboards ADC input. Take 3.3V from one board only.
- if you use UART, then send the same data to both boards, again common GND.

**Comment by interlark** [comment]
Thanks for reply. Okay, so it doesn't matter whether I place wheels like (HWWx = x-th hoverboard's wheel):
```
[HWW1 LEFT] - [HWW1 RIGHT]
[HWW2 LEFT] - [HWW2 RIGHT] 
```
or
```
[HWW1 LEFT] - [HWW2 RIGHT]
[HWW1 LEFT] - [HWW2 RIGHT] 
```
?

**Comment by EmanuelFeru** [comment]
It does matter. You can use the arrangement you prefer, just make sure to comment/un-comment in `config.h` the following defines to match your setup:
```
 #define INVERT_R_DIRECTION                // Invert rotation of right motor
 #define INVERT_L_DIRECTION                // Invert rotation of left motor
```

**Comment by interlark** [comment]
@EmanuelFeru Thank you, mate!

**Comment by SchO2n** [comment]
> Depends how are you controlling it and what is your input. The idea is to have both mainboards receive the same input. Just some examples (didn't try myself):
> 
> * if you used ADC as input, then you have to make the 2 mainboards GND common, and connect the potentiometer(s) output to both mainboards ADC input. Take 3.3V from one board only.
> * if you use UART, then send the same data to both boards, again common GND.

Hello, can we link the two GND of the motherboards if they are powered by two different batteries? Tks
