### ISSUE TITLE
 VARIANT_TRANSPOTTER power off

### ISSUE THREAD

**Issue by GigiBoot** [EmanuelFeru/hoverboard-firmware-hack-FOC#163]
Hello,

I have a problem with  VARIANT_TRANSPOTTER, I can't power off the board from the Power button.
Power_on works as intended but when I try to power off, it makes 2 beeps on different tone each time and the speed is changed.
I had tried automatic shutdown after 1 min. but still no luck.
Is it a compiling /programming error?
I am using https://pionierland.de/hoverhack/ to compile it.

Thanks!

**Comment by Candas1** [comment]
Please check the wiki

**Comment by GigiBoot** [comment]
Indeed it was there: short press followed by long press.
Thank you!

**Comment by Candas1** [comment]
You're welcome, this information was added recently ;)
