### ISSUE TITLE
Support for Gen2 Board

### ISSUE THREAD

**Issue by szepnorbee** [EmanuelFeru/hoverboard-firmware-hack-FOC#165]
No plans to support this new "Gen2" board? Unfortunately, it is the cheapest available at the moment and it's the one I have.

![Hardware_Overview_small](https://user-images.githubusercontent.com/3252103/115889339-25019180-a454-11eb-8865-7db54044e87d.png)

**Comment by Candas1** [comment]
Hi 

No plan, there is another firmware available for those boards, please check the wiki:
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility
