### ISSUE TITLE
Variant USART et ESPHOME

### ISSUE THREAD

**Issue by BSD31** [EmanuelFeru/hoverboard-firmware-hack-FOC#166]
Bonjour et félicitation pour cet excellent travail.
J'ai utilisé la variante ADC pour piloter la carte de mon hoverboard et ça fonctionne parfaitement.
J'ai maintenant un autre projet avec un ESP32 et ESPHOME.
ESPHOME permet de programmer facilement des ESPxx.
Il est ensuite très facile d'intégrer le montage dans la solution domotique open source Home Assistant.
Auriez-vous déjà travaillé avec ESPHOME et auriez vous un exemple de code pour faire fonctionner l'hoverboard directement depuis Home assistant ?
Merci de votre aide.

Hello and congratulations on this excellent work.
I used the ADC variant to drive my hoverboard board and it works perfectly.
I now have another project with an ESP32 and ESPHOME.
ESPHOME makes it easy to program ESPxx.
It is then very easy to integrate the assembly into the open source Home Assistant home automation solution.
Have you ever worked with ESPHOME and have sample code to run the hoverboard directly from Home assistant?
Thank you for your help.

**Comment by Candas1** [comment]
Hi, 

I haven't heard about anyone using this firmware with ESPHOME.
You can control the firmware through an esp32 with usart variant, there are details in the wiki.

**Comment by BSD31** [comment]
Thank you for that answer.
I'm looking on my own but if anyone has already implemented this firmware with ESPHOME, that would be great.

**Comment by Candas1** [comment]
If you join the telegram group linked in the main page you can ask to the community.

**Comment by BSD31** [comment]
Excellent idea. 
I just joined the group. 
I will put my question to it immediately.
Thank you
