### ISSUE TITLE
Q: Wich is the best control method from Arduino? ... and why ?

### ISSUE THREAD

**Issue by mrlunk** [EmanuelFeru/hoverboard-firmware-hack-FOC#177]
Hi again all :)

As mentioned in the title:
Q:  Wich is the best control method from Arduino? ... and why ?

- PWM
- PPM 
- UART

GreetZ,
Peter Lunk

**Comment by Candas1** [comment]
Hi,

Please explore the wiki.
You will get to know more about the firmware and find the answer to your question

**Comment by Candas1** [comment]
And the main page also 😜

**Comment by mrlunk** [comment]
Well I can send all three from an arduino with some effort...
Why is UART advised ?

**Comment by Candas1** [comment]
Have you read this ?
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Variant-USART

You see that the transmission errors are rejected, you can get feedback data, ....

**Comment by mrlunk** [comment]
Ah ok, ...
So sending PWM or PWM would not give any feedback data ?

(I can program failsafes for PWM RC data transmission fails too)

PL.
