### ISSUE TITLE
ESP32 FOC Hoverboard Forum

### ISSUE THREAD

**Issue by vamfun** [EmanuelFeru/hoverboard-firmware-hack-FOC#178]
This is not an issue but it would be nice to have a place for  EmanuelFeru FOC hoverboard users employing ESP32 in their prototypes to have a forum like space to share there knowledge.
Perhaps this issue could remain open for that.  What do you think?

**Comment by mrlunk** [comment]
Have you found the Telegram group ?
Link is at the bottom of the readme page ;)
PL.

**Comment by EmanuelFeru** [comment]
We can use Telegram (for quick qestions, sharing results) and with Github for Topics that should be saved and probably help others in the future.
A forum can also be done if someone wants to take initiative.
