### ISSUE TITLE
 out of control when pwm wire lost

### ISSUE THREAD

**Issue by jpfree** [EmanuelFeru/hoverboard-firmware-hack-FOC#180]
thank you very much for your work and contribution。

I encountered a very terrible thing, when the PWM line of the receiver is broken or the receiver fails, the wheel will turn uncontrollably. It's the same with raspberry pi When raspberry pi restarts, 

i must connected the pwm line to the raspberry first,then  power on the raspberry，and  power on the board,it will work fine。

how can I add an initial PWM signal to the firmware? Similar out of control protection function, thank you

**Comment by EmanuelFeru** [comment]
It is most probably moving because the line is floating and it's detecting false pwm pulses. 
You can try to add 100k pull down resistors, so the timeout functionality will trigger and as a result the motors will stop.

**Comment by Candas1** [comment]
Hi

Using pulldown resistors was also suggested in the telegram group.
Also I was asking why using PWM variant from a raspberry pi when you can use [USART](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Variant-USART) Variant ?
