### ISSUE TITLE
Forward Sideboard data through usart to Arduino or Raspberry PI

### ISSUE THREAD

**Issue by PaddyCube** [EmanuelFeru/hoverboard-firmware-hack-FOC#187]
First of all, thank you so much for this great project and the resources you share. You equip so many people with new possibilities to re-use hoverboard hardware and thinker around.

**What can we do to make the firmware better?**
From my understanding, motors can be controlled by usart and by using one or both sideboards. If using one sideboard, we can attach RC receivers to control the motors. Is it also possible to just forward MPU data over main PCB to an Arduino or Raspberry PI using USART? Also is it possible to just forward LED commands to an attached sideboard

**Describe suggestions or alternatives you have considered**
I'm working on a robot which uses a Raspberry Pi as main MCU. As we are limited with USART interfaces on a Raspberry PI, it would be great, if we can just forward any messages from/to sideboard without interfacing to motors. This way, we can re-use the MPU and LED/Sensors of sideboard without adding new one to the Raspberry PI directly.

**Comment by EmanuelFeru** [comment]
Hi, I'm happy to hear you like it.

> Is it also possible to just forward MPU data over main PCB to an Arduino or Raspberry PI using USART?

I think it is better to read the MPU data directly Arduino - Sideboard. Otherwise there will be communication delays.

> Also is it possible to just forward LED commands to an attached sideboard

Yes, you can already send a byte to the sideboard, where each bit indicates which LED to light up. Check the received structure by the sideboard.
