### ISSUE TITLE
Switch between control modes without reprogramming

### ISSUE THREAD

**Issue by Hylke33** [EmanuelFeru/hoverboard-firmware-hack-FOC#189]
### Your System
- VARIANT: UART3
- CONTROL TYPE: FOC_CTRL
- CONTROL MODE: TRQ_MODE / SPD_MODE

I wonder if it is possible to switch between the different control modes without reprogramming the controller. I want to control the controller via UART, so if would be possible with a command that would be awesome.

**Comment by Candas1** [comment]
Check this
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/issues/143
