### ISSUE TITLE
Checksum in Arduino Code

### ISSUE THREAD

**Issue by blubbi321** [EmanuelFeru/hoverboard-firmware-hack-FOC#19]
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/fb362f04a9544fdeb3f569726408623cc4ecfa41/02_Arduino/hoverserial/hoverserial.ino#L61

needed to change this to uint16 to make it work. 

However there still seem to be a lot of transmission errors. (I get problems in every 5-6th received string)

**Comment by EmanuelFeru** [comment]
You are right, I will do the change soon.

**Comment by EmanuelFeru** [comment]
fixed.
