### ISSUE TITLE
Hoverboard model

### ISSUE THREAD

**Issue by rdignoti** [EmanuelFeru/hoverboard-firmware-hack-FOC#192]
Can you provide me a link for the hoverboard model that have the same motherboard you are using?

Thanks

**Comment by Candas1** [comment]
Hi. 

It's not clear what hoverboard has what motherboard unfortunately.
I think we had better luck with older hoverboards. 
To drive the cost down, they came up with hoverboards with different mainboards, different chips, cheaper wheels, smaller batteries.

[Wiki](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility) explains what boards are compatible with this firmware.

**Comment by rdignoti** [comment]
Thank you, seems like a russian roulette buy a brand new hoverboard, much better second-hand ones

**Comment by Candas1** [comment]
I bought many second-hand ones, and got a lot of split boards.
So you can sell it if you are not happy with the board inside.
