### ISSUE TITLE
feedback speed

### ISSUE THREAD

**Issue by s56jsc** [EmanuelFeru/hoverboard-firmware-hack-FOC#204]
What is relationship between enter speed parameter and Feedback.speed that I got from serial?
Example. If I send "Send(0,xx)" I got "Feedback.speedL_meas =yy" 
xx ---> yy
.-------
10 -->  4
50 --> 15
100 --> 45
500 --> 310
900 --> 570

I did my own PID code for motor and look that it work well. But now I need to synchronise feedback speed with input speed.

best regards

**Comment by Candas1** [comment]
Input is speed in rpm only if you use speed mode
