### ISSUE TITLE
Motors dont start

### ISSUE THREAD

**Issue by Michael0yodi** [EmanuelFeru/hoverboard-firmware-hack-FOC#207]
### Your System
- VARIANT: Denver
- CONTROL TYPE: Hoverboard 
![image](https://user-images.githubusercontent.com/29892040/129026411-2e12089f-bc7b-4962-a34e-f58a1ee1cb86.png)

Hi,

Im trying the hoverboard firmware build, it looks like the sensor board communicate since it changes color but no movement whatsoever on the motors, I tried to change the  baud;
USART2_BAUD     32100
USART3_BAUD     32100 

Since it was mention that some "Denver" might use this but with this setting I did not get any respons from the sensor boards
It do play poweron/powerdown melody and led goes from red to green while pressing the plates
![image](https://user-images.githubusercontent.com/29892040/129029010-226985ee-691b-475a-8271-9172e6a0e9e1.png)

Any ide what I might have done wrong?

**Comment by Candas1** [comment]
You mean you flashed the firmware to use the hoverboard as a hoverboard ?
But this is not implemented yet.
