### ISSUE TITLE
Motors spinning at max speed

### ISSUE THREAD

**Issue by AleLinox** [EmanuelFeru/hoverboard-firmware-hack-FOC#224]
### Your System
- VARIANT: USART 
- CONTROL MODE: SPD_MODE
- What is your application? Four wheeled robot

Hi everyone, I'm currently trying to flash Emanuel's firmware on the board in the picture. The main control is an GD32F103, compatible with the firmware and in fact I'm normally using this on another board. But on this one when I turn on the supply the motors start to spin to max velocity 
![immagine](https://user-images.githubusercontent.com/73386894/134024935-51a60807-5bf1-496f-ba0d-e24c40f842f4.png)
and I don't understand way. Can someone help me?

**Comment by Candas1** [comment]
I think @EmanuelFeru once mentioned this can happen in speed mode when hall sensors are not mapped in the way expected by the firmware. So the firmware reads a speed with an opposite sign, and increases the torque to reach commanded speed, but will never reach it and limits at max rpm. You probably need to find the right hall sensor mapping.

**Comment by AleLinox** [comment]
Yeah, after erasing multiple times and changing the hall sensors position now all works fine. Thanks @Candas1
