### ISSUE TITLE
Add deadband to PPM variant

### ISSUE THREAD

**Issue by bionic24** [EmanuelFeru/hoverboard-firmware-hack-FOC#29]
The standard PPM code does not include deadband. Since the input from the receiver is rarely a true zero, you will see some jittering and wheels will rotate instead of staying in neutral position when no throttle is required.

Benjaf has created a fix for this (although PWM) in his fork of the original firmware hack. https://github.com/benjaf/hoverboard-firmware-hack-esk8. Hopefully this can be integrated in the FOC firmware as it is in my opinion quite essential for a proper functional PPM variant.

From line 125 in control.c the following code has been added:.
https://github.com/benjaf/hoverboard-firmware-hack-esk8/blob/9aca8c7939ec418b41ac4995fb3cfb2911dfd727/Src/control.c#L125-L135

In config.h the amount of deadband is set with the following line of code:
https://github.com/benjaf/hoverboard-firmware-hack-esk8/blob/9aca8c7939ec418b41ac4995fb3cfb2911dfd727/Inc/config.h#L69

Also, but perhaps this just a feature request. In current settings the motors will actively brake on 1500ms signal, but on e-boards most people would want to freewheel at 0 throttle and brake with reverse. Benjaf modified this piece of code in main.c
https://github.com/benjaf/hoverboard-firmware-hack-esk8/blob/9aca8c7939ec418b41ac4995fb3cfb2911dfd727/Src/main.c#L282-L287

**Comment by EmanuelFeru** [comment]
Done.
