### ISSUE TITLE
Gyro

### ISSUE THREAD

**Issue by slip11** [EmanuelFeru/hoverboard-firmware-hack-FOC#34]

**Comment by EmanuelFeru** [comment]
Can you explain the issue?

**Comment by slip11** [comment]
Hi, the brake does not work, just de-energizes the motors. But at maximum speeds sometimes includes reverse) 
P.S. Poti calibrated using debug

**Comment by EmanuelFeru** [comment]
I am not sure if I understand... What variant are you using? When do you see issues and what kind?
