### ISSUE TITLE
I added your three firmwares to my online compiler :-)

### ISSUE THREAD

**Issue by RoboDurden** [EmanuelFeru/hoverboard-firmware-hack-FOC#35]
https://www.pionierland.de/hoverhack

i dream you like it :-)

**Comment by EmanuelFeru** [comment]
Awesome. Thanks!
In the next commit, I will add your link in the Readme (I hope not to forget).

**Comment by pav18** [comment]
Good job. You have saved a lot of our time!!!!

**Comment by pav18** [comment]
> Awesome. Thanks!
> In the next commit, I will add your link in the Readme (I hope not to forget).

And your firmaware is awesome (compiled online) ;)  All works as expected. Next step is to parallel two boards and I will have 4WD ;)  Thanks to @NickLD who suggested me your firmware.
