### ISSUE TITLE
Mode switch

### ISSUE THREAD

**Issue by pav18** [EmanuelFeru/hoverboard-firmware-hack-FOC#40]
Would you add Mode switch via UART please? Just to make possible switching between Speed and Torq.
Thank you.

**Comment by yashatan** [comment]
You can change control mode easily by changing ctrlModReq variable. 2 for Speed and 3 for Torq.
Add 1 more variable to your serial Frame and then read them to change ctrlModReq as you want.

**Comment by EmanuelFeru** [comment]
Hi @pav18 , I agree with @yashatan solution, use that and you should be fine.
