### ISSUE TITLE
Beeper

### ISSUE THREAD

**Issue by pav18** [EmanuelFeru/hoverboard-firmware-hack-FOC#41]
Would you add hoverboard Beeper control via UART? 
Thank you.

**Comment by yashatan** [comment]
You can add it by yourself easily, there are shortBeep() function and longBeep() function, just call it whenever you want. And just like control mode, you can add 1 mỏe variable about beeper and just read it in mainboard.

**Comment by EmanuelFeru** [comment]
Hi @pav18 , I agree with @yashatan solution, use that and you should be fine.
