### ISSUE TITLE
Turn On/Off

### ISSUE THREAD

**Issue by pav18** [EmanuelFeru/hoverboard-firmware-hack-FOC#42]
I use two hoverboards in my 4WD project. I control boards via ESP32. Use 2 UARTs. When I push power button at main board (where ESP takes power), the second board also switches on (surprise). BUT when I push button again only main board switches off but second still working.
I think that everything could be controlled software.
Is it possible to add feature to turn off second board when main board receive command to switch off (hard button)?
Is it possible to implement UART switch OFF?
Thank you.

**Comment by yashatan** [comment]
> Is it possible to implement UART switch OFF?

I think yes it is. You can call [poweroff()](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/master/Src/util.c#L547) function to switch off your board.

**Comment by EmanuelFeru** [comment]
Thanks a lot  @yashatan  for support.

**Comment by pav18** [comment]
> Or just simple connect 2 button port of both to ONE button

is it safe?

**Comment by pav18** [comment]
> Thanks a lot @yashatan for support.
@EmanuelFeru is it possible to add turnoff, beep to default UART firmware. Friendly speaking I am not a programmer at all and all this look a little bit complicated for me. I use online compilator for your firmware and like it very much. But it would be nice if you put everything inside the firmware. Best,

**Comment by yashatan** [comment]
@pav18  do you have telegram or whatsapp, i will help you code it

**Comment by pav18** [comment]
> @pav18 do you have telegram or whatsapp, i will help you code it

+7 nine 1 seven ... 5 ... seven 9 8....five six... 5   I would appreciate your help.

**Comment by yashatan** [comment]
Why don't you just type your number? why "nine" "seven"...?

**Comment by pav18** [comment]
@yashatan  not to let searching machines index it ;)  Both and whatsapp and telegram

**Comment by yashatan** [comment]
ok i have add you

**Comment by waythe** [comment]
hi @pav18 , 
have you finished your project and would you mind sharing some experience since I am just having the same trouble with you.
I've written my problems in https://github.com/EFeru/hoverboard-firmware-hack-FOC/issues/256
