### ISSUE TITLE
Control wheels separately

### ISSUE THREAD

**Issue by pav18** [EmanuelFeru/hoverboard-firmware-hack-FOC#43]
For better start I want to implement some kind of traction control or something like that. If one of the wheels slips the torq shall be decreased for this wheel.
Any suggestions how to do it? At present time I Send(0,1000) via UART so there are no personal torq values for each wheels. Or I can play with steer?

**Comment by yashatan** [comment]
You can use cmd1 for left and cmd2 for right. At [mixerFcn()](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/master/Src/util.c#L1067) you can make speed -> speed for left and steer -> speed for right.
