### ISSUE TITLE
Hoverboard firmware

### ISSUE THREAD

**Issue by moezmahroug** [EmanuelFeru/hoverboard-firmware-hack-FOC#44]
Hi,
I'm a new member of this wonderful forum. I would like you to help me find a solution to my problem, please!

So, my problem is that I purchased Hoverboard for robot projects. Unfortunately, I discovered that it is not original. My project is to control their motors with Arduino. So, I tried to work on it, but I made a mistake and I lost the firmware. There are three CPUs and I only work with one of them. I will mention it in the pictures.
If you can help me get him back to work as they were or given me a solution to control it with Arduino for a robot project ( forward, backward, turn left, and right, with variable speed).
I would be very grateful.

type of board => YK95 V1.1

![placa-de-controle-pcb-principal-placa-mae-yk95-para-hoverboard-pecas-equilibrio-inteligente-scooter-eletrico-6-5-8-10-polegada-r (1)](https://user-images.githubusercontent.com/64503922/80656920-3cdd4a00-8a7a-11ea-8fed-e44bcc52d4d3.jpg)
![placa-de-controle-pcb-principal-placa-mae-yk95-para-hoverboard-pecas-equilibrio-inteligente-scooter-eletrico-6-5-8-10-polegada-r (2)](https://user-images.githubusercontent.com/64503922/80656932-4070d100-8a7a-11ea-9676-121c9686fc6e.jpg)
![placa-de-controle-pcb-principal-placa-mae-yk95-para-hoverboard-pecas-equilibrio-inteligente-scooter-eletrico-6-5-8-10-polegada-r](https://user-images.githubusercontent.com/64503922/80656935-41a1fe00-8a7a-11ea-9acd-b9b42d28d05d.jpg)

**Comment by EmanuelFeru** [comment]
Once the firmware is erased, there is no way to recover it (as far as I know).

The board you have is not a standard board, so I don't know what will happen if you use my FOC firmware. However, I have seen people compiling the firmware on such boards, but don't take it as 100% true. I think you should check the microcontroller pinouts before flashing to avoid breaking stuff.

**Comment by moezmahroug** [comment]
Hi,
Thanks a lot for the quick answer.
This is my mistake, I tried to open its protection, but the memory was erased. I think I will try to drive the MOSFET drivers at first if it's ok a will move on to get signals from hall sensors.
I will try to find a program running on Arduino to control the MOSFET drivers. If you have any links for a program I can use it.

Something like this in the picture : 

![arduino-bldc-motor-sdsdsdcircuit](https://user-images.githubusercontent.com/64503922/80867425-cdd73f80-8c8b-11ea-9171-00ff01f6aae2.png)
