### ISSUE TITLE
Steering not working on PWM

### ISSUE THREAD

**Issue by emilhse** [EmanuelFeru/hoverboard-firmware-hack-FOC#56]
Hi everyone, I'm new in all of this. i tried PWM version I compiled successfully but no mater what i do steering is not working.Throttle is working. Also with using potentiometers   everything working well. can you please advise me how can fix it?

**Comment by benjaf** [comment]
The code for PWM steering seems to be based on the wrong version of my fork. The working PWM steering is found in this version of [control.c](https://github.com/benjaf/hoverboard-firmware-hack-esk8/blob/RC-Steering/Src/control.c).
You should be able to just overwrite the whole CONTROL_PWM section (line 118 onwards).
I would submit a pull request, but I have no way to verify if the code i actually working right now.

**Comment by EmanuelFeru** [comment]
@benjaf  it would be great if you can provide a pull request.  I might have ported the wrong code for the steering channel.

**Comment by benjaf** [comment]
@EmanuelFeru I got the RC receiver working with my gokart so the changes could be tested. I have submitted a pull request with the fixed version!

**Comment by EmanuelFeru** [comment]
Awesome! I will have a quick look and merge. Thanks!

**Comment by EmanuelFeru** [comment]
@emilhse is fixed. You can give it a try. Thanks a lot @benjaf !

**Comment by emilhse** [comment]
Thanks a lot gentlemen !!!!!!!!!!!
