### ISSUE TITLE
simple firmware to flash with stm32cubeprogrammer

### ISSUE THREAD

**Issue by mihaigabriel620** [EmanuelFeru/hoverboard-firmware-hack-FOC#60]
hello i want a firmware with foc control to use on my hoverboard with no mods
just as a hoverboard
and to have all 3 modes selectable by pussing different times the power button
and ho hold the power putton to power off
pressing will just change the modes
PLS DO THAT

**Comment by Chaos99** [comment]
Commutation and sinusodial (which defaults to commutation for slow speeds) will not work well for a balancing applications. I will offer a pull request for balancing in FOC mode in a few weeks, but it will not be a ready-made solution for hoverboards. More work need to be done for this.

**Comment by mihaigabriel620** [comment]
Thanks i hope it will be possible

**Comment by EmanuelFeru** [comment]
Balancing control is not yet available. Bipropellant did some work in that direction and some other people as well. So, fell free to also contribute in this direction.
The features that you want related to the buttons are too application specific, so you have to implement them yourself for your own application.

@Chaos99 I didn't know you are focusing on balancing controller. Nice to hear, I think is an interesting control problem to solve.

**Comment by mihaigabriel620** [comment]
Im a noob to coding i just have the stm32 snd the software
