### ISSUE TITLE
Joystick control

### ISSUE THREAD

**Issue by farev** [EmanuelFeru/hoverboard-firmware-hack-FOC#66]
Hello, this project was really helpful for me it is the only hoverboard-hack code that runs smoothly. I am building a mini go-kart and I want to control with an analog joystick I tried setting up the code for this but I couldn't, I can't control it very well. Can someone please help to set it up correctly for my analog joystick. 

Or is there a tutorial or instructions I can follow to correctly controll it with an arduino?

**Comment by EmanuelFeru** [comment]
I'm happy to hear that you like the project. 
What type of joystick do you have? And I am a bit confused when I read Arduino and joystick together, what is the Arduino purpose?

As a side note you can also use 2 pedals with VARIANT_HOVERCAR of the firmware which is all already completely ready to use. You can check the Hovercar video in Readme page to see how it looks and if you like it.

**Comment by farev** [comment]
I am using an analog joystick, that is just two potentiometers together. 
A picture of the joystick:
[https://www.google.com/search?q=analog+joystick&rlz=1C5CHFA_enGT877GT877&sxsrf=ALeKk01HagegYZcXhoeEO0exbg4JlSgH7Q:1592511648157&source=lnms&tbm=isch&sa=X&ved=2ahUKEwin0dqYmIzqAhVOn-AKHUIkDxEQ_AUoAXoECAwQAw&biw=1417&bih=671#imgrc=vSuR7hnQ3RTpAM](url)

When I mentioned to use an arduino I meant that if there are instructions I can follow to controll it with arduino instead of the joystick, because I do not know how to set it up correctly.

**Comment by EmanuelFeru** [comment]
For joystick control is very easy:
- just select VARIANT_ADC in platformio.ini [here](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/85552b3e41f383475990a26f85ae4290f571388e/platformio.ini#L12-L20)
- then uncomment MID potentiomenters in config.h [here](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/85552b3e41f383475990a26f85ae4290f571388e/Inc/config.h#L227-L231)
- connect take the Left sensor cable (long wired) and connect your joystick, GNG to GND, one line to X joystick, the other line to Y joystick and take 3.3V from from the programming port. 
- Do not connect the red wire from the sensor board, it carries 15V! And it will burn the microcontroller. Also double check that the Black sensor wire is indeed GND, some boards have the wiring messed up.
- flash the firmware and give it a try
- at some point, you will have to calibrate your joysticks ADC readings to get it working properly, check config.h for more details

On the other hand, I still consider that pedals are more suitable for Go Karts. You can buy 2 of these for example:
https://www.banggood.com/custlink/mmG32e8i46

**Comment by farev** [comment]
Than you, only how do I select VARIANT_ADC in platformio.ini, do I just remove the semi colon?

**Comment by EmanuelFeru** [comment]
yes

**Comment by farev** [comment]
I was able to get it all set up but it isn't working properly. It moves when it is at the center and when I move it forward or to the side it does not move the motors as it should.

**Comment by EmanuelFeru** [comment]
When is at the center it moves because the ADC is not calibrated. And what do you mean by "not moving as it should"?

**Comment by farev** [comment]
Likw when I try to move forwars only one motor moves forward, or when I try to turn it stops, it does different mivements than the ones to turn, or to move forward.
 How do I calibarate it? Maybe that is the problem.

**Comment by EmanuelFeru** [comment]
Have a look here:
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/85552b3e41f383475990a26f85ae4290f571388e/Src/util.c#L398-L406

**Comment by farev** [comment]
I did it but it is still the same.

**Comment by farev** [comment]
Also when I turn it on it doesn't move until a little while after I start randomly moving the joystick.

**Comment by farev** [comment]
I tried with a normal potentiometer and I calibarate it and I found out that both motors ,when trying only the speed, don't roatate at the same speed.

**Comment by EmanuelFeru** [comment]
Can you try to swappin the motor wires? Sounds like the motor wires or hall sensors are not mapped correctly.
Also if you make a short video it will be easier to understand what is going on.

**Comment by farev** [comment]
Here is a video:
[Video.zip](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/files/4805313/Video.zip)

**Comment by EmanuelFeru** [comment]
From the video looks like the motor phases are not correct (even thought the colors are ok). Try swapping them. Apply small input and check how it behaves.

**Comment by farev** [comment]
I tried sawapping the mtor wires and when it started moving it inmediatly turned off. I think my motherboard died because it doesn’t turn on any more.

**Comment by farev** [comment]
It doesn't turn on with the button, I tried another button and nothing, but it does turn on if I connected to my computer with 3.3v connected. What may have happenned here?

**Comment by EmanuelFeru** [comment]
I think one of the TIP27 might be damaged. Can you check it with an oscilloscope?

**Comment by farev** [comment]
I got it to turn on again but the motors are still not moving correctly. I tried different phase mapping and it still dirrent work.

**Comment by EmanuelFeru** [comment]
did you fixed it?

**Comment by farev** [comment]
Yes, it turns on now but I still can't controll it correctly with the joystick. Do you know if someone else has tried to use an analog joystick?

**Comment by farev** [comment]
Now the mainboard turns on and makes the sound but it then immediately turns off without making any sound. How do I check if a TIP27 is damaged with my multimeter? I tried it but couldn't figure out if something was wrong.

**Comment by EmanuelFeru** [comment]
If it doesn't hold power on, then one TIP27 I guess is damaged. You can check them for continuity, I think one of them is shortened.

**Comment by farev** [comment]
Some of them are passing like 0.2 or 0.7v and others are passing the complete voltage of the battery.

**Comment by EmanuelFeru** [comment]
That I am not sure. Maybe you are better at electronics than me:
https://www.st.com/resource/en/datasheet/tip120.pdf

For me when they broke they were usually shortened.

**Comment by joedeveloper** [comment]
Just FYI, I did a quick test with a cheap analog joystick connected to Arduino and then sending the massaged values to the hoverboard via uart, this works for me. Personally I find using direct connect adc joysticks potentially dangerous - I haven't tried on this firmware, so maybe the calibration / deadband / out of range logic is solid. The problem with wired joysticks are manyfold - from induction, to handling physical wear and tear a runaway condition can happen both on shorts and disconnects etc.

My plan is to have an esp32 connect to the hb over uart, then process control data from a wireless source - at least then you know you have to deal with out of bounds data gracefully.

**Comment by farev** [comment]
Thank you for your help, could you send an example of your arduino code please. I have never used uart with an arduino.

**Comment by joedeveloper** [comment]
I modified the arduino sample included in this repo only very slightly:
https://gist.github.com/joedeveloper/8b26ffa01f513a67e004164667ced5bc

the values I add / subtract here are specific to the cheap joystick I am using for testing.

**Comment by EmanuelFeru** [comment]
I agree that joysticks resting at middle could be more dangerous. Normally, you should solder pull down resistors on the ADC pins, so in case of wire disconnection, the value is pulled down, making the ADC go out of range and by that it will go to a safety state.
For this protection the ADC_PROTECT_ENA needs to be activated in config.h

The classic potis resting at the lower bound (not middle) are safer to me.

Of course, depends on the application is better to work with digital signals. Like it was mentioned esp32, no need for ADC calibration, and the signal can be very clean, depending of the input source, for e.g. your smartphone or other digital device connected to the esp32.

**Comment by farev** [comment]
Can I use a bluetooth hc05 or hc06 module the same way as a esp32?

**Comment by EmanuelFeru** [comment]
I am not familiar with the bluethooth module, but I see they output UART data. What is the format of the UART data? Can it be programmed?
Because the mainboard expects a certain UART data format. ESP32 gives can be programmed so it is quite flexible, but I am not sure if the hc05 can be programmed or not.

**Comment by farev** [comment]
No I would have to use an arduino to use it.

**Comment by farev** [comment]
I am trying to control it directly from the arduino but I can't get it to move. Does the arduino need a seperate power source or can I connect it to the 3.3v in the mainboard?

**Comment by EmanuelFeru** [comment]
For testing, you can power the Arduino externally. Use the example sketch.

**Comment by farev** [comment]
I couldn't get the test working with the arduino, it just beeps.

**Comment by EmanuelFeru** [comment]
What Variant are you using. Make sure you connected the arduino to the right cable and wires. Tx to Rx, Rx to Tx.

**Comment by farev** [comment]
I am using the USART Variant and I connected it correctly, do I need to connect the gnd too?

**Comment by EmanuelFeru** [comment]
Yes, sure. Otherwise there is no proper TX RX high and low level, it would be just floating input.

**Comment by farev** [comment]
Even with the gnd connected the motors don't move when I try using the arduino.

**Comment by EmanuelFeru** [comment]
That is strange.. in my testing it worked. Is there a posibility to check with an oscilloscope or an FTDI debuger to check if data is send from Arduino Tx, that data is send from Mainboard Tx?

**Comment by farev** [comment]
Could this be happenning because of a faulty motherboard? I don't if my motherboard couldbe fualty.

**Comment by EmanuelFeru** [comment]
If the melody is playing and the board turns on off properly, I think the board is ok.

**Comment by farev** [comment]
I tried several times but I can't get it to work with the arduino, I tried checking with the arduino serial monitor if it was recieving and sending correctly but it didn't print what it should. The rx light in the arduino lights up but the tx doesn't, could the arduino be the problem?

**Comment by EmanuelFeru** [comment]
On the Arduino did you use pin 2 and 3? Those are the pins that should go to the main board not Tx and Rx (see the Arduino code)

**Comment by farev** [comment]
So I got the test running it worked fine, but when I tried it with the joystick and the modified arduino code it didn't work. It moved the wheels very little and not smoothly.

**Comment by EmanuelFeru** [comment]
What was the issue?

**Comment by EmanuelFeru** [comment]
Arduino code must be a bit optimized, that is just an example. Better is to do the sending in a periodic interrupt.

**Comment by farev** [comment]
To get the test working I had to reflash again the motherboard becuase I found out that if you conected the pins wrong one time you had to flash it again to make it work. How do I do the sending in periodic interrupt?

**Comment by EmanuelFeru** [comment]
https://www.instructables.com/id/Arduino-Timer-Interrupts/

**Comment by farev** [comment]
I still couldn't get it to work with the arduino and the joystick even trying with periodic interrupt.

**Comment by tmichele** [comment]
> For joystick control is very easy:
> 
> * just select VARIANT_ADC in platformio.ini [here](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/85552b3e41f383475990a26f85ae4290f571388e/platformio.ini#L12-L20)
> * then uncomment MID potentiomenters in config.h [here](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/85552b3e41f383475990a26f85ae4290f571388e/Inc/config.h#L227-L231)
> * take the Left sensor cable (long wired) and connect your joystick, GNG to GND, one line to X joystick, the other line to Y joystick and take 3.3V from from the programming port.
> * Do not connect the red wire from the sensor board, it carries 15V! And it will burn the microcontroller. Also double check that the Black sensor wire is indeed GND, some boards have the wiring messed up.
> * flash the firmware and give it a try
> * at some point, you will have to calibrate your joysticks ADC readings to get it working properly, check config.h for more details

Hi Emanuel, i followed every step:
- uncommented variant_adc at row 12 of platformio.ini
- uncommented row 226 and 230 of config.h
- flashed the motherboard with success (when i connect the battery it plays the melody)
Then i connected power and hall sensors to a motor and connected joystick to 3.3v (from programming port), gnd blue and green cable from left sensor.

When i move the joystick nothing happens.
What am i doing wrong? Is it ok to keep the power button jumpered all the time? If i connect the battery without jumpering the power pins it plays the melody and then it starts beeping

Thank you in advance.
![image](https://user-images.githubusercontent.com/25886069/86537951-0812c680-bef3-11ea-8b87-99514c9d2ea1.png)


Ps: every few minutes the motherboard beeps once.

**Comment by EmanuelFeru** [comment]
Hi, it is not ok to keep button pressed all the time because it will get stuck in button pressed function. Press the button only during programing.

The beeping is most probably because the pots are not calibrated.

**Comment by tmichele** [comment]
Ok, i flashed the motherboard while keeping pressed the power button (jumper), then i removed the jumper and disconnected the battery.
Then i've reconnected the original power button.

Now when i plug the battery the melody plays and then it start beeping (intermittent) even with no cable connected other than battery, is that ok?
While beeping i tried the _Auto-calibration of the ADC Limits_ but when i restart the board it plays the melody then it start intermittent beeps again.

**Comment by EmanuelFeru** [comment]
Probably the calibration didn't succeed. Can you connect to serial debug and check the ADC values?

**Comment by farev** [comment]
What values can I send from the arduino to make the motors move?

**Comment by EmanuelFeru** [comment]
Initially you have to send 0 for the motors to enable, then you can send other values to spin them.

**Comment by farev** [comment]
What is the range of the values? Is it from 0 to 255?

**Comment by EmanuelFeru** [comment]
For the motors [-1000, 1000]

**Comment by farev** [comment]
So, I got it working with the joystick but it only works while the arduino is connected to my computer.

**Comment by farev** [comment]
Ok I got it working I changes the arduino code and now it works fine. It is very sensible, so for some applications it might be dangerous, but you can change the motors max speed very easily. There is a lot of commented code, this are some things I tried to make everything run even smoother but I left it there if someone wants to work on it. 

Link to my code: 
https://github.com/farev/Arduino-Code-for-Hoverboard-FOC-control)

**Comment by diogoc** [comment]
I have a problem where the wheels still rotate a little with the joystick in the center position.
I have done manual calibration and automatic calibration.
It has improved but a small touch on the joystick and the wheels no longer stop completely.
Is it possible to add a deadband around the center, in which the movement of the wheels is zero?

**Comment by farev** [comment]
I have the same problem, although I am using an arduino to smooth out the joystick signals. Do the motors only move forward or do they move kinda randomly?

**Comment by diogoc** [comment]
They move ramdomly. 
The joystick is very sensitive too. I think it is configurable with this parameters:
DEFAULT_RATE   
DEFAULT_FILTER         
DEFAULT_SPEED_COEFFICIENT
DEFAULT_STEER_COEFFICIENT
but I dont know how adjust and what they really mean. Is there some more detailed explanation?

**Comment by farev** [comment]
What joystcik are you using? I have the same problem that the motors move randomly when my joystick is at 0, I think that may be a problem with the code or a physical problem with the motherboard.

**Comment by diogoc** [comment]
it is a joystick like that:
[https://www.banggood.com/JoyStick-Module-Shield-2_54mm-5-pin-Biaxial-Buttons-Rocker-for-PS2-Joystick-Game-Controller-Sensor-p-1566502.html](url)

**Comment by farev** [comment]
I am using the exact same joystick, yes it is very sensitive and when it is directly connected to the motherboard it sometimes accelarates really fast. That is why I changed to using it with an arduino.
