### ISSUE TITLE
connection board 

### ISSUE THREAD

**Issue by bekirbostanci** [EmanuelFeru/hoverboard-firmware-hack-FOC#71]
Hi 
I did'nt connect with the hoverboard st link. I tried with connect stlink utilty but it was not work. 
What is the problem do you think?
![image](https://user-images.githubusercontent.com/26343575/85756200-45b76880-b717-11ea-8b50-88f7fe009506.png)

**Comment by EmanuelFeru** [comment]
Wrong pin connection maybe.. Check with a multimeter

**Comment by KaanDemirkoparan** [comment]
Firstly he asked me about problem. And I checked everything (connections, stlink etc.) and they seems to be fine. He does every step right but it still gives that error. We couldn't solve it. Do you have any idea?

**Comment by EmanuelFeru** [comment]
Have you tryied anothe ST link or another chip?

**Comment by bekirbostanci** [comment]
yes i tried with stm32f103 (blue pill) and it worked

**Comment by EmanuelFeru** [comment]
Have you tried with another main board too? Maybe the MCU is dead :(

**Comment by bekirbostanci** [comment]
hoverboard is working, i controlled :(

**Comment by EmanuelFeru** [comment]
That is strange

**Comment by EmanuelFeru** [comment]
your mcu is really strange. I haven't seen such a thing before. I don't know what can be done more.

A yes, I know, cut your MCU out very carefully, clean the pads. Order new MCU and solder it on. You can find them on Aliexpress for quite cheap in batches. I did that already and I recommend.

**Comment by bekirbostanci** [comment]
Yes, thank you for recomandation. I want to add information, I did not try but someone says that; boot0 pin should goes to and reset the card after the this process, you can erase.  
I dont now but it can work thaks again
