### ISSUE TITLE
GD32F103RCT6 flashing

### ISSUE THREAD

**Issue by trondin** [EmanuelFeru/hoverboard-firmware-hack-FOC#79]
Hi,
is any difference for GD32F103RCT6 flashing? Or I have to use it as  STM32F103RCT6 in PlatformIO?

**Comment by EmanuelFeru** [comment]
As far as i know both can be flashed the same with no additional change. GD32 seems to be a clone of the STM32.

**Comment by trondin** [comment]
Thanks, it really works without any problem. The board had survived :)

**Comment by bekirbostanci** [comment]
i have same mcu and flashing give this alert "Read out protection is activated".
I tried Target > Option Bytes > Read Out Protection > Enable than apply but 
16:10:06 : Option bytes updated successfully.
16:10:06 : Can not read memory!
                 Disable Read Out Protection and retry.

Do you have any idea about this problem ?

**Comment by trondin** [comment]
Are you sure your system powered from battery, not from programmer - I have killed one processor by powering from programmer. After processor replacement the main board is functional again - but it was different board, STM32 based. For GD32F103RCT6 protection was remover without any problem.

**Comment by bekirbostanci** [comment]
@trondin I tried again and solved problem thank you
