### ISSUE TITLE
Error in the calculation of input from ADC causing fixed point overflow

### ISSUE THREAD

**Issue by JulienKx** [EmanuelFeru/hoverboard-firmware-hack-FOC#8]
The calculation of input value from raw ADC in the following line can cause incorrect value :
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/62873aad578a20834bc4c036954801f2b4fb23cd/Src/main.c#L280

When ADC_MIN > 0 and raw ADC value > ADC_MAX, cmd will be > 1000 (the maximum allowed value normally).
When raw ADC value is very above ADC_MAX and ADC_MIN is not very small, you can get cmd value > 2047.

When cmd is then converted to fixdt(1,16,4) in the following code, an overflow occurs and final output value is negative, causing reverse operation.

https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/62873aad578a20834bc4c036954801f2b4fb23cd/Src/main.c#L307-L313

To correct this issue, the first referenced line has to be replaced by :
`cmd2 = CLAMP(adc_buffer.l_rx2 - ADC2_MIN, 0, ADC2_MAX - ADC2_MIN) * 1000 / (ADC2_MAX - ADC2_MIN);  // ADC2`
or simpler and more clear :
`cmd2 = CLAMP((adc_buffer.l_rx2 - ADC2_MIN) * 1000 / (ADC2_MAX - ADC2_MIN), 0, 1000);  // ADC2`

Of course, the same has to be done for cmd1.

**Comment by EmanuelFeru** [comment]
Fix done (I like the suggested approach, more simple and clear)
Topic can be closed.
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/01a08d5f6d71d98a57d554623c2567eb8ac583cb/Src/main.c#L269-L281
