### ISSUE TITLE
Arduino Control Advice?

### ISSUE THREAD

**Issue by fender90** [EmanuelFeru/hoverboard-firmware-hack-FOC#83]
Dear @EmanuelFeru 
Sorry to disturb you  :-)
I know that this is not an issue and you do not have to answer this kind of dumb questions but I hope you could help me with this.
I have modified the Arduino code to connect an RC receiver to it (I know that there is a PPM or PWM mode in the firmware but as I am going to change to other input options later). When trying to increase the throttle or steering the motors do not react then start to spin randomly. When releasing the joysticks the motors stop with a great delay. Each time the spinning direction is different.
Could you please advise? I don't understand what I did wrong here. Would appreciate your help very much.
[Here is the link to the modified code 
](https://github.com/fender90/hoverduino/blob/master/hoverboardarduino.ino)

**Comment by EmanuelFeru** [comment]
There is no visible issue in the code. However, I suggest some check to find the cause of the problem:
- first, check that the original Arduino example works. It should ramp up and down the motors smoothly
- Serial print ch2, ch3 to see if they are read correctly
- check that for the middle of ch2, ch3, you indeed get 0 in hoversteer,  hoverspeed

**Comment by fender90** [comment]
> There is no visible issue in the code. However, I suggest some checks to find the cause of the problem:
> 
> * first, check that the original Arduino example works. It should ramp up and down the motors smoothly
> * Serial print ch2, ch3 to see if they are read correctly
> * check that for the middle of ch2, ch3, you indeed get 0 in hoversteer,  hoverspeed

Dear @EmanuelFeru thanks for your reply.

The original example works and I get a correct feedback
I will add a deadband just in case so that ch2 and ch3 are not centered they would not  cause the motors to spin.
