### ISSUE TITLE
Need help with wiring up variant adc with esp32

### ISSUE THREAD

**Issue by Justiudios** [EmanuelFeru/hoverboard-firmware-hack-FOC#91]
Hey,
i need some help wiring up variant adc with esp32.

I connected a joystick to the left sideboard cable and can control the board. But if i replace the joystick with my esp32, it doesn't seem to react to different V inputs.
I checked the output of my GPIO25 using a multimeter and it changes the way i programmed it. (from 0 to 3.3V)
![wiringESP](https://user-images.githubusercontent.com/31997805/90684452-82f82c80-e268-11ea-9784-451212c81218.jpeg)

Can someone improve my wiring or help me? :)

**Comment by Candas1** [comment]
Hi,

Why would you use adc between esp32 and the board, you can use USART.
There is a sample arduino sketch.

**Comment by Justiudios** [comment]
Hey, 
unfortunate i didnt get it to work with uart too. 

I will give it a try again. Can you give me some information about wiring to use uart? 

Thanks

**Comment by Candas1** [comment]
yes it will be a better solution.
If it's beeping it means UART communication is not ok (wrong speed, wrong frame, ... )

**Comment by Justiudios** [comment]
Wow, it just works. Dont know what i did wrong last time. Thanks for the push into the right direction ^^
