### ISSUE TITLE
VARIANT_ONEWHEEL

### ISSUE THREAD

**Issue by vfear** [EmanuelFeru/hoverboard-firmware-hack-FOC#93]
a few days ago, I completed the onewheel project.  I used the factory firmware from a hoverboard and combined the two motors into one.  the body was assembled from aluminum pofil and plywood, and the motors were inserted into a go-kart tire.  it turned out a lot of fun) but still want to make a custom firmware and add several functions to it: increase the speed, raise the nose of the board when gaining speed.  it's hard for me to make such a firmware on my own, since I don't know much about programming, but if you could help, I think it would be interesting to a lot of people

**Comment by EmanuelFeru** [comment]
@vfear I think the balancing controller can be used for onewheel as well. However, it is not finalized yet, so it will take some time. At the moment, my time is limited on this project. I can only spend little time to do some improvements.

**Comment by vfear** [comment]
@EmanuelFeru Hi, I found this example http://www.cammservices.com/projects/onewheelboard. Arduino + mpu6050 + VESC. Is it possible to make such a project for working with hoverboard mainboard?

**Comment by annoyinganime** [comment]
Using stock hoverboard motor you can expect 16-18km/h at most, that's a KV limitation of the motor. I was able to rework the wiring inside the motor to triple that speed, however it reduced the torque by the same amount. For my electric longboard it was worth it, but I don't think that's a great option for you, because gyro-stabilized electric vehicles (at least as I know it) should have great torque to be able to stabilize themselves

**Comment by EmanuelFeru** [comment]
This Variant will be covered when the Balancing controller is implemented in the VARIANT_HOVERBOARD.

**Comment by tonymande** [comment]
I'm also interested in the VARIANT_HOVERBOARD and VARIANT_ONEWHEEL, which doesn't exist yet. Maybe I could help. I modified your code already for the Hovercar and although I'm not really familiar with programming arm chips, I've done much programming for Arduino. So I'll give it a try.

@EmanuelFeru: Could you pinpoint me to the code of the balancing controller? What method is your implementation based on (PID)?

**Comment by EmanuelFeru** [comment]
@tonymande I am happy to hear you want to support. I think if you have Arduino programming skills then you will be doing fine with STM.

I have then some material for you :-)
1. Tan @yashatan worked on this for his graduation project using fuzzy controller, so he already figured out the signs and [orientation matrix for the sensors](https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/blob/89719ae4f6a25cda4ce39548c9417557522fce21/Src/mpu6050.c#L55-L57). His reositories are here:
https://github.com/yashatan

2. I already did a simulation model (work in progress) with the balacing control structure as below. My intention is to design a controller in simulation and then build code from it.
![image](https://user-images.githubusercontent.com/24780745/102008565-dc153000-3d31-11eb-8028-88d014ca05f6.png)


3. It is inspired from here:
[MiniBalanceV3.5 karlman filter.zip](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/files/5684428/MiniBalanceV3.5.karlman.filter.zip)

**Comment by tonymande** [comment]
Thanks for the information. Yes, I'll open another item once I can get my hands on it.

**Comment by vfear** [comment]
> Thanks for the information. Yes, I'll open another item once I can get my hands on this topic.

any news?
