### ISSUE TITLE
VARiENT_HOVERBOARD doesnt work .... Just Beeping!

### ISSUE THREAD

**Issue by Persiahoverboard** [EmanuelFeru/hoverboard-firmware-hack-FOC#95]
I Programmed my Main and the side boards
One Stm32f103 on the main
And two GD32f130 for both sides
I checked the Gyro chip (MCU-6050)

Any idea?

**Comment by EmanuelFeru** [comment]
VARIANT_HOVERBOARD is not finalized (also mentioned in ReadMe) because the balancing controller has not yet been implemented. So, it could be that you get beeping since the angle values are not processed.
Other variants are tested and should work.

**Comment by EmanuelFeru** [comment]
Duplicate with #62
